export const fullNameMapping: Record<string, string> = {
    FRA: 'Frankfurt Airport',
    FCO: 'Leonardo da Vinci-Fiumicino Airport',
    JFK: 'John F. Kennedy International Airport',
    LAX: 'Los Angeles International Airport',
    LHR: 'Heathrow Airport',
    CDG: 'Charles de Gaulle Airport',
    AMS: 'Amsterdam Airport Schiphol',
    BCN: 'Barcelona-El Prat Airport',
    DXB: 'Dubai International Airport',
    IST: 'Istanbul Airport',
    SFO: 'San Francisco International Airport',
    DFW: 'Dallas/Fort Worth International Airport',
    ATL: 'Hartsfield-Jackson Atlanta International Airport',
    ORD: 'Chicago O\'Hare International Airport',
    SIN: 'Singapore Changi Airport',
    PEK: 'Beijing Capital International Airport',
    PVG: 'Shanghai Pudong International Airport',
    HKG: 'Hong Kong International Airport',
    BKK: 'Suvarnabhumi Airport',
    ICN: 'Incheon International Airport',
    NRT: 'Narita International Airport',
    HND: 'Haneda Airport',
    MAD: 'Adolfo Suárez Madrid–Barajas Airport',
    DME: 'Domodedovo International Airport',
    VKO: 'Vnukovo International Airport',
    LGW: 'Gatwick Airport',
    STN: 'London Stansted Airport',
    LCY: 'London City Airport',
    MAN: 'Manchester Airport',
    EDI: 'Edinburgh Airport',
    GLA: 'Glasgow Airport',
    BRU: 'Brussels Airport',
    ORY: 'Orly Airport',
    LIN: 'Milan Linate Airport',
    MXP: 'Malpensa Airport',
    MUC: 'Munich Airport',
    BER: 'Berlin Brandenburg Airport',
    ZRH: 'Zurich Airport',
    GVA: 'Geneva Airport',
    VIE: 'Vienna International Airport',
    LPA: 'Gran Canaria Airport',
    PMI: 'Palma de Mallorca Airport',
    TFS: 'Tenerife South Airport',
    AUH: 'Abu Dhabi International Airport',
    DOH: 'Hamad International Airport',
    SAW: 'Istanbul Sabiha Gökçen Airport'
    // Add more mappings as needed
};
